### ISSUE TITLE
Default palettes? (and styles in general)

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#25]
Does it make sense to store a default palette for a given parameter? I have a feeling that for some coverages the data creators have a clear idea how to visualize it, and this would create uniform output. Examples would be land cover and digital elevation models. Also, maybe such palettes could be stored more centrally for reuse (when seen through LD glasses). For continuous data, the most important thing is probably the middle palette point, which may be required to correspond to 0 for some data.

**Comment by jonblower** [comment]
Yes, this could be a useful addition, as long as it is optional of course. We might want to think more widely about styles that are not colour palettes (e.g. contours etc), but palettes are a good start. Use cases might include:

 1. For DEM data, there are some well-known palettes (e.g. blue for stuff below sea level, then a progression of greens, browns and whites for the land, with increasing altitude).
 2. Vegetation data, which might use a specific set of greens and browns.
 3. Some remote sensing folk in sea surface temperature use a standard colour palette (with fixed endpoints) so that plots can be directly compared between groups.
 4. Data representing fractions, e.g. if the value range is [0,1] or [-1,1].

It could also be useful to use the semantics of the parameter name, e.g. if the quantity is detected to be a fraction then the client could automatically select an appropriate colour palette, even if it's not externally specified.

**Comment by neothemachine** [comment]
I have a feeling that this should not be in the core CoverageJSON spec but rather in some extension spec since it is fairly complex. I will close this for now and we may come back to that in a separate repo, maybe coveragejson-styling or whatever.
