### ISSUE TITLE
Regular domain axes

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#30]
The request for a regular axis encoding pops up again and again, so it's time to think of a way of encoding those.

A regular axis can be encoded efficiently by defining the start, end, and spacing. How to encode bounds for regular axes is not immediately clear, a default (always has bounds) cannot be assumed, and custom bounds for each cell don't make sense, so it is probably just a boolean like "hasBounds". Any other things to consider?

One particular use case is curvilinear grids where the actual latitude/longitude coordinates are represented as parameters/range, and the domain just has index-type X/Y axes (`[0,1,2,3,4,...]`). And obviously those domain axes should not occupy unnecessary space since they won't be used in most cases (as often those don't have a known geographical CRS).

This issue is related to https://github.com/Reading-eScience-Centre/coveragejson/issues/24. Here I will try to use the relevant new syntax.

First, several ways to represent the regular axis values:

Variant 1 (whether stop is included or not has to be defined):
```js
"start": 45,
"stop": 55,
"step": 0.5
```
(see [numpy.arange](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html))

Variant 2  (whether stop is included or not has to be defined):
```js
"start": 45,
"stop": 55,
"num": 20
```
(see [numpy.linspace](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html))

Variant 3:
```js
"start": 45,
"step": 0.5,
"num": 20
```

I kind of lean towards the third one as it is not ambiguous at all. But I see that the first one is how it's done in GML and would also make the end-point directly obvious. The second variant is probably out of the race.

Including such properties in a domain axis could look like:
```js
"domain": {
  "axes": {
    "y": {
      "values": [45, 46, 47, ...], // optional if others are given
      "start": 45,
      "stop": 55,
      "step": 1
    }
  }
}
```

It should also be possible to define that on time strings. The fact that an axis is made of time strings would be put inside the referencing field. So:

```js
"start": "2012-01-01T00:00:00Z",
"stop": "2012-01-02T00:00:00Z",
"step": "PT30M" // ISO8601 duration
```
I think using ISO8601 durations is fine since they can be parsed easily using the popular [moment.js](http://momentjs.com/docs/#/durations/creating/) library.

How does that look? What about bounds?

**Comment by jonblower** [comment]
I think GML goes with the start-stop-step one because each one has a physical meaning (the "step" is the resolution). The problem is that floating-point imprecision can mean that `num = (stop-start)/step` turns out not to be an exact integer. So I tend to like the variants that include "num" explicitly. Actually my favourite is the option you rejected (start-stop-num) because the overall bounds of the axis are there explicitly.

Regarding bounds, I would suggest providing four options. In all cases, the bounds appear half-way between each axis value:
 1. Extend bounds half a step at both start and end of axis (probably the most common cases)
 2. Don't extend bounds at all (probably second most common case)
 3. Extend bounds half a step for only the low end of the axis
 4. Extend bounds half a step for only the high end of the axis.

The last two are quite unlikely to occur.

If you wanted a more unusual case you could provide an option to specify the bounds explicitly as an array (very unlikely I think, in fact I can't think of a use case).

**Comment by neothemachine** [comment]
Actually, `num` has another advantage. It works with ISO times more easily. You could just convert start and end to a unix timestamp (with float part) and then calculate your steps easily in that number space. So it eliminates the need for a ISO8601 duration string parser.

About bounds, what about WaterML2 things where a value applies to the last interval? That basically means the bounds end and start at the coordinate steps.
Also, your second option, would the first and last cell then be only half size? Is that really common?

**Comment by jonblower** [comment]
> About bounds, what about WaterML2 things where a value applies to the last interval?

Do you mean that in WaterML2 the values are applied to the intervals in general (not just the last interval) rather than the "cell" centres? So in this case the axis values would actually be the bounds, not the cell centres?

I think that we could have the convention that:
 1. If bounds are not provided, values are associated with the axis values
 2. If bounds are provided, values are associated with the intervals (i.e. all positions within the interval are mapped to the same data value). In this case the axis values are probably not really needed, but may be necessary to indicate the centres of the intervals for the benefit of plotting routines that need axes to be collections of points.

> Also, your second option, would the first and last cell then be only half size? Is that really common?

Yes, the first and last cells would be half size. Maybe this wouldn't happen for regular axes, come to think of it. It might be more common for irregular axes, where the extrapolation outside the first and last coordinate values is not so well defined.

**Comment by jonblower** [comment]
Oh, and we have to be careful with ISO times and intervals/durations if we want to be strictly accurate. Leap seconds can mess things up. A Duration of 1 day (P1D) may not always be of the same length in seconds.

But, having said this, I'm not sure whether ISO8601 uses a calendar system that includes leap seconds. (Chris Little would be the person to ask about all this!)

**Comment by neothemachine** [comment]
WaterML2:
![WaterML2](https://cloud.githubusercontent.com/assets/530988/10963641/e197fde8-8399-11e5-94e9-e390cebb79f0.PNG)
Not sure if you really meant that, but that's what I mean.

I don't understand your two bounds conventions really. Can you give a short example with 3 coordinates and bounds?

Leap seconds... that problem would apply to both `num` and `step` encodings. Well, then `num` may even have more issues with that, whereas for `step` we could say that the ISO duration string can only have seconds, minutes, or hours, nothing above that like days due to ambiguity. Although as you say it depends on the calendar if it has leap seconds at all.

I see the first signs of complication compared to simply listing all axis values! ;)

**Comment by jonblower** [comment]
I guess for time durations we should say that the axis can only be regular if it is truly regular in terms of "real" durations (like milliseconds, seconds etc). If there are leap seconds involved the axis could simply have the values spelled out individually instead of the start/stop/num shorthand.

OK, for the bounds conventions. I'm going to try to explain this via the medium of ASCII art!

Assume that the axis values are [0,1,2,3,...] and the corresponding range values are [a,b,c,d,...]. Imagine that the axis is a function f(axis value). So:
 * f(0) = a
 * f(1) = b
 * etc.

The question is, what is f(1.5)? This would depend on the convention for interpolating values between the axis values. I'm using the pipe (`|`) to indicate where the bounds are.

**Case 1:** Range values associated only with axis values:

```
   a     b     c     d    
|--0--|--1--|--2--|--3--|--
```

f(0) = a
f(1) = b
f(1.2) = null (undefined)

**Case 2:** Range values associated with intervals:

```
 aaaaa bbbbb ccccc ddddd    
|--0--|--1--|--2--|--3--|--
```

f(0) = a
f(1) = b
f(1.2) = b
f(2.9) = d

In this case we would need cell_methods to determine whether the values are averages over the interval, or something else.

This is using the NetCDF convention where axis values are associated with the centres of the cell. In WaterML2 it seems that the axis values are associated with the bounds, something like this:

```
 aaaaa bbbbb ccccc ddddd    
|----0|----1|----2|----3|--
```

But in this formulation, how do you know where the left-hand boundary of the first cell is?

**Comment by neothemachine** [comment]
About WaterML2, they have special metadata for identifiying the start/end boundary of the first/last cell: startAnchorPoint, endAnchorPoint

**Comment by jonblower** [comment]
So, in WaterML, if you have `n` data points, you have `n` axis values, which can either represent the start or end of an interval. If the axis values represent the start of an interval, you also need an `endAnchorPoint`. If the axis values represent the end of an interval, you need a `startAnchorPoint`. Is that correct?

This seems odd to me, but perhaps this is because a common use case in WaterML is to measure aggregations (e.g. of rainfall or river flow) that are recorded at the end of a time period?

**Comment by neothemachine** [comment]
> So, in WaterML, if you have |n| data points, you have |n| axis values, 
> which can either represent the start or end of an interval. If the 
> axis values represent the start of an interval, you also need an 
> |endAnchorPoint|. If the axis values represent the end of an interval, 
> you need a |startAnchorPoint|. Is that correct?
>
Yes, I think that's correct. Although they also allow per-point metadata 
to set the interval length with "aggregationDuration". What they have is 
the most efficient representations for their domain. In 
CoverageJSON/netCDF-CF the "bounds" are a lot more general but also take 
up more space.

> This seems odd to me, but perhaps this is because a common use case in 
> WaterML is to measure aggregations (e.g. of rainfall or river flow) 
> that are recorded at the end of a time period?
>
That seems like the reason, it's quite specific, even in the (possibly 
more general) OGC Timeseries profile draft.

**Comment by neothemachine** [comment]
About bounds... the tricky thing is that if you wanted to define regular bounds similar to the axis coordinates, then that would imply that there are no holes and neighbouring bounds share their edges, for example:
```js
{
  "start": 0, "stop": 100, "num": 101,
  "bounds": {
    "start": -1.0, "stop": 100, "num": 102
  }
}
```
(This would be last-day average WaterML2-like bounds, if the numbers were times...)

But if you want to give them explicitly, then you would define two bounding coordinates for each axis coordinate:
```js
{
  "start": 0, "stop": 100, "num": 101,
  "bounds": {
    "values": [-1.0,1.0, 1.0,2.0, 2.0,3.0, ...]
  }
}
```
And this may be confusing since it looks similar to the axis coordinates but in fact behaves differently. Maybe the "values" version must have an extra field that says if you're using connected boundaries or not.

**Comment by jonblower** [comment]
I think by far the common case (for grids at least) is that bounds will touch each other and be halfway in between the axis values. It may be worth having a shorthand for this (e.g. “bounds” : “regular”) or something like that.

If you want to explicitly give bounds that don’t touch, how about a 2D array. I think this might be what CF does, but I’m not sure:

```
“bounds” : {
  “values” : [ [-1.0,1,0], [1.5,2.5], …]
}
```

**Comment by neothemachine** [comment]
So what about the WaterML2 case? If that's a regular axis, would you force people to spell out the explicit bounds because they don't touch in the middle of the axis values? That was my idea with the regular bounds object above (`"start": -1.0, "stop": 100, "num": 102`).

Also... maybe we can restrict the regular axis notation to coordinate axes (numbers), and for anything else you have to be explicit, just to prevent algorithms messing up being slightly off. I'm looking at time strings in particular, I just don't see an easy way to calculate the time steps while considering all the possible issues with times like leap seconds etc. But of course if you used a temporal CRS, then these issues don't exist, and you could use the regular axis encoding again. It also fits better when you would allow various other strings like IDs as domain values.

**Comment by jonblower** [comment]
Yes, I think regular axes should be confined to numeric axes.

For WaterML2, I was thinking something like this, where the axis values are at the end of the bounds. This is probably what you meant;

```
"values": [1, 2, 3, 4, 5, 6, ...]
"bounds": [[0,1], [1,2], [2,3], ...]
```

This saves all the stuff about "startAnchorValue" or whatever WaterML2 defines.

**Comment by neothemachine** [comment]
Ok so how would you call the shorthand half-way-bounds? I have a feeling "regular" is not specific enough, since your WaterML2 example is also regular.

**Comment by jonblower** [comment]
Er, I don't know. I agree "regular" is not good enough. We could use "bounds" : "default" and then define what that means in the spec?

**Comment by neothemachine** [comment]
I'm closing this for now. I added the regular axis encoding (without bounds) to the spec and implemented it. As a regular encoding for bounds seems to be more tricky, I'll defer that until we really need it. An explicit listing of bounds is already possible.
