### ISSUE TITLE
Units vs quantities (vs CPM "property")

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#39]
Currently we only specified units for parameters. However, [quantities](https://en.wikipedia.org/wiki/List_of_physical_quantities) are the bigger concept behind them. For example, "Area" is a quantity with a standard/canonical unit of "m^2", and the unit of measurement may be "mm^2". It seems to me that this is pretty similar to the "property" in the complex properties model, which for example is "Temperature". They also have a canonical unit field now. What are the cases where "property" != "quantity"?

**Comment by neothemachine** [comment]
Just found this comment in http://sweet.jpl.nasa.gov/2.3/propQuantity.owl:
> Quantitative properties are Quantities

So I guess "property" is indeed the right abstract term to cover both quantities and other things. I was just wondering because the qudt ontology just has units and quantities, so that means it is focused on quantitative properties only.

What is an example of a property that is not a quantity? Is that anthing which is not a number? Like landcover categories?

**Comment by neothemachine** [comment]
From the http://sweet.jpl.nasa.gov/2.3/propTemperature.owl ontology:
```xml
  <owl:Class rdf:about="#ElectronTemperature">
    <rdfs:subClassOf rdf:resource="#Temperature"/>
    <rdfs:subClassOf>
      <owl:Restriction>
        <owl:allValuesFrom rdf:resource="&part;#Electron"/>
        <owl:onProperty rdf:resource="&crela;#hasSubstance"/>
      </owl:Restriction>
    </rdfs:subClassOf>
  </owl:Class>
```

I'm not sure what I should make of this. It seems that here a property is actually what a complex property is in CPM, while the most base property is what corresponds to CPM's "property", but in fact it is just a subclass relation.

So, given that, if "temperature" is a property, and is also a complex property, what would the "property" of CPM then be? In the ontology above, the superclass of Temperature is ThermodynamicQuantity. Should that go there? It seems a bit arbitrary to do it like that. Or is CPM in fact a limited model that may not always work?

**Comment by adamml** [comment]
I would say "temperature" is the property, it is not - in and of itself - a complex property. It can fill in the property / quantity portion of the model, but "temperature" has no matrix etc...

I'm not quite sure what they're trying to say with "ElectronTemperature" in SWEET.

Is it that the matrix of the temperature measurements described is "electrons" (as opposed to "water" or "atmosphere") or is it that there is a resticiton on the "Temperature" measurement in a matrix of, for example, "water" so that only the "electrons" have their temperatures measured?

e.g.

```
<http://example.org/#ElectronTemperature> a cpm:ObservableProperty;
    cpm:property <sweet:Temperature>;
    cpm:matrix <sweet:Electron>
```

or

```
<http://example.org/#ElectronTemperature> a cpm:ObservableProperty;
    cpm:property <sweet:Temperature>;
    cpm:restriction <sweet:Electron>
    cpm:matrix <http://example.org/#Water>
```

**Comment by adamml** [comment]
> They also have a canonical unit field now.

Not quite yet - see https://github.com/adamml/opm-owl/issues/1

I'm still waiting for details on a CF namespace as I really think that would be the best place to serve the canonincalUnit predicate from.

**Comment by neothemachine** [comment]
You said temperature is not a complex property. In fact, sweet says temperate "measureOf" Heat. Where heat is defined in sweet as ThermodynamicQuantity. Wouldn't that qualify as a property for temperature?

We can probably find many more examples like that. The real question therefore is (I think): What exactly is a complex property and what not? I'd like to have a clear definition you can look up somewhere. Also, a definition of what exactly the "property" field should be. Whether that's a kind of parent property of the complex property or something else.

**Comment by jonblower** [comment]
I'm going to wave a big flag saying "Rabbit hole!!" This is certainly interesting and of wider importance but I don't think it's our job to fix it. I had a look into units and quantities etc a while ago (there was a Java library that handled this kind of thing nicely) but came to the conclusion that a generic solution would be pretty tough to implement. Apart from anything else, most people just don't publish this level of information with their data, so we're unlikely to be able to improve this with CoverageJSON. I think we should see if a "winner" emerges from the ontologies out there.

And, for CoverageJSON v1 at least, I think we are fine with:
 * `observedProperty` (URL to external definition outside our control)
 * `description` (explanation of property in natural language, could be used instead of, or as well as, the `observedProperty`, or could duplicate the definition for convenience
 * `unit` (The actual unit used)
 * Perhaps `canonicalUnit` too, although I'm not sure how we would actually use that.

I think it's actually more important for us (practically speaking) to figure out how we're going to serialise the unit string. UCUM? UDUNITS? We need this in order to do unit conversions accurately.

**Comment by neothemachine** [comment]
Closing this for now. Unit formats are done in the linked issue. Further CPM related discussion should happen in the https://github.com/adamml/opm-owl issues.
