### ISSUE TITLE
Split up range into fragments?

### ISSUE THREAD

**Issue by jonblower** [Reading-eScience-Centre/coveragejson#49]
I think this would be an idea for later, but I wanted to capture it now. To help serving large ranges in a scalable fashion, maybe the rangeSet could offer different URLs for different fragments of the range. Something like this (very rough sketch):

```
"rangeSet" : {
  "TMP" : {
    "fragments" : [{
      "shape" : "0:1,*,*", // numpy-like slice syntax
      "data" : "http://my.url.link/fragment1"
    },{
      "shape" : "1:2,*,*",
      "data" : "http://my.url.link/fragment2"
    }]
  },
  "UVEL": {
  ...
  }
}
```

This might do something like serving each depth level as a different fragment, if the range is in zyx axis order. I can see that this could get a bit complex for clients, but may be manageable? It's inspired by the "Linked Data Fragments" kind of idea, where they try to increase the scalability of servers and push a little more intelligence to the client.

**Comment by neothemachine** [comment]
Jeremy (@6a6d74) mentioned this idea at the CEO-LD meeting as well but I don't remember the details. It was more focused on pre-defined coverage subsets I think, so at a higher level possibly. This would be in contrast to a server API that can serve any kind of subset. It touches aspects of the REST API but also CovJSON, and I think it would be something that is built into CovJSON itself.

**Comment by jonblower** [comment]
Has Jeremy picked a hex code as his GitHub id? ;-)

I think Chris Little is thinking about this as "coverage tiles" or "cubelets" or something like that. I think there are two ways of doing it:
 1. Make each fragment a fully-fledged coverage in its own right, or
 2. Just subset the range (which is what I've done above).

Option 2 is simpler (perhaps), particularly for "simple" lat-lon-depth data cubes. But it doesn't work so well where an axis of the coverage doesn't have a sensible ordering. For example, a point cloud coverage would have a single "location" axis, whose values are xyz tuples in an arbitrary order. It would be more sensible to subset this coverage in geospatial coordinates, not in index space. Hence in this case it may be better if the fragments are full coverages.

Maybe both options are possible, for different use cases. 

(Also, it may be possible to order the tuples in the point cloud along some kind of space-filling curve, which means that subsetting in index space does return points that are typically close to each other in real space. But I digress...)

**Comment by neothemachine** [comment]
For range-based subsetting, how about...
```js
"ranges" : {
  "TMP" : {
    "type": "NdArrayPartition",
    "axisNames": ["t","y","x"],
    "shape": [2, 100, 100],
    "parts": [{
      "slice" : [null,null,null],
      "url" : "http://example.com/cov1/temperature.covjson"
    },{
      "slice" : [0,null,null],
      "url" : "http://example.com/cov1/temperature_2010.covjson"
    },{
      "slice" : [1,null,null],
      "url" : "http://example.com/cov1/temperature_2015.covjson"
    },{
      "slice" : [0,[0,50],[0,50]],
      "url" : "http://example.com/cov1/temperature_2010_nw.covjson"
    },{
      "slice" : [0,[0,50],[50,100]],
      "url" : "http://example.com/cov1/temperature_2010_ne.covjson"
    },{
      "slice" : [0,[50,100],[50,100]],
      "url" : "http://example.com/cov1/temperature_2010_se.covjson"
    },{
      "slice" : [0,[50,100],[0,50]],
      "url" : "http://example.com/cov1/temperature_2010_sw.covjson"
    },{
      "slice" : [1,[0,50],[0,50]],
      "url" : "http://example.com/cov1/temperature_2015_nw.covjson"
    },{
      "slice" : [1,[0,50],[50,100]],
      "url" : "http://example.com/cov1/temperature_2015_ne.covjson"
    },{
      "slice" : [1,[50,100],[50,100]],
      "url" : "http://example.com/cov1/temperature_2015_se.covjson"
    },{
      "slice" : [1,[50,100],[0,50]],
      "url" : "http://example.com/cov1/temperature_2015_sw.covjson"
    }]
  }
}
```
The idea is that overlapping slices can be defined, based on numpy slicing semantics. `null` means that the axis is not sliced (`*`), a simple number means exactly that index is picked, and a two-number array means `from:to` with `to` exclusive. Of course, the latter would also cover all cases but I think it is more human readable that way, more compact, and not harder to process really (very simple to normalize in clients if needed). It is overlapping to support multiple client access patterns, where all are optional but all indices have to be covered at least once. In the example above the supported access patterns are:
- load the whole range data
- load a time slice
- load a geographical box of a time slice where four boxes make up the whole time slice.

The `"url"` would link to an embedded range document, currently only `"NdArray"`, but could also be a sparse variant in the future.

By defining a separate range type "NdArrayPartition" this would be easily distinguishable in clients. The standalone profile would not allow this range type since it is not embedded, keeping the standalone profile simple.

I think this should be baked into the spec for 1.0 since it is very straight forward and not really surprising or controversial, compared to the trickier task of specifying pre-defined subsets in coordinate space on the coverage level.

It should be noted that this is a low-level data access mechanism and not in any way useable for identifying/linking to (coverage) subsets on a semantic level.

**Comment by jonblower** [comment]
This looks good to me. A few questions:

 2. What would one of the "child" documents look like? For example if the `shape` of the top-level Range is `[2, 100, 100]` and we have a child document that holds a single timeslice (`[0,null,null]`), what would we use for the `shape` and `axisNames` properties of the child document? And what about the more complex slices (e.g. `[1,[50,100],[50,100]]`)?

 3. Could range documents be arbitrarily nested in this way? I.e. an `NdArrayPartition` document could point to another `NdArrayPartition` document, and so forth. Or would this be too complex for clients? If we don't want this, we should explicitly disallow it I suppose.

 5. I agree that it would be good to bake this into version 1.0 when we're sufficiently confident. Would it make clients much more complicated, if they have to understand all the possibilities here?

 6. Just to be clear, we are saying that each range subset contains values for only one parameter, right? I don't suppose it's worth considering allowing values for multiple parameters to exist in the subset? I guess not - it would presumably make the structure more complicated.

 4. Would it be useful to specify the type of the child document when giving its URL? E.g.:

```js
{
  "slice" : [1,[50,100],[0,50]],
  "url" : "http://example.com/cov1/temperature_2015_sw.covjson",
  "type": "NdArray"
}
```

It would then be possible to give the same range subset in two different structures (e.g. NdArray, SparseArray) and clients could select between them.

**Comment by neothemachine** [comment]
After discussions from yesterday, here's Jon's idea:
```js
"ranges" : {
  "TMP" : {
    "type": "TiledNdArray",
    "axisNames": ["t","y","x"],
    "shape": [2, 100, 100],
    "tileSets": [{
      "tileShape": [null, null, null],
      "tileTemplate": "http://example.com/cov1/TMP.covjson"
    },{
      "tileShape": [1, null, null],
      "tileTemplate": "http://example.com/cov1/TMP/byyear/{t}.covjson"
    },{
      "tileShape": [null, 20, 20],
      "tileTemplate": "http://example.com/cov1/TMP/bybbox/{x}-{y}.covjson"
    }]
  }
}
```
This would then have to be repeated for each parameter, which is fine I think.

An example tile is then just a regular `NdArray` document.
For example `http://example.com/cov1/TMP/byyear/0.covjson` would be:
```js
{
  "type": "NdArray",
  "dataType": "float",
  "axisNames": ["y","x"],
  "shape": [100, 100],
  "values": [...]
}
```
And if/once we introduce sparse ndarrays, then there could be an intelligent mix of sparse and dense ndarrays, such that tiles with lots of missing data (or no data at all) can be made sparse and very compact.

I also had an idea on how to identify index-based subsets in the context of a coverage. Basically, [fragment identifiers](https://en.wikipedia.org/wiki/Fragment_identifier). For example, `http://example.com/cov1.covjson#t=0` or `http://example.com/cov1.covjson#x=10,50&y=20,30` (from 10 to 50). Then this would logically identify that particular fragment of the coverage which is determined by index-space subsetting. Could be useful for RDF folks, and also for clients which could then, if they see such a URL with a fragment, just load that particular part by whatever means, e.g. the tilesets. The indices in the fragment are not the tile indices, they are the real axis indices. I guess this could then be extended to parameter selection as well, which may mean that the index fragment stuff above has to be encapsulated maybe. Like `http://example.com/cov1.covjson#index(x=10-50&y=20-30),parameter(TMP)`.

**Comment by neothemachine** [comment]
Answering to some earlier questions:


> Could range documents be arbitrarily nested in this way? I.e. an `NdArrayPartition` document could point to another `NdArrayPartition` document, and so forth. Or would this be too complex for clients? If we don't want this, we should explicitly disallow it I suppose.

I would say this should not be allowed for simplicity.

> I agree that it would be good to bake this into version 1.0 when we're sufficiently confident. Would it make clients much more complicated, if they have to understand all the possibilities here?

I think by structuring it into tile sets it gets easier than in my proposal, because clients don't have to worry about overlapping tiles. The test of course is to try to implement it.

> Just to be clear, we are saying that each range subset contains values for only one parameter, right? I don't suppose it's worth considering allowing values for multiple parameters to exist in the subset? I guess not - it would presumably make the structure more complicated.

Yes, multiple parameters are too complicated probably. Also, with HTTP/2 those "issues" get less relevant since there is way less too-many-requests overhead then.

> Would it be useful to specify the type of the child document when giving its URL? It would then be possible to give the same range subset in two different structures (e.g. NdArray, SparseArray) and clients could select between them.

This would introduce another layer. I think publishers should just choose the most suitable range type and clients are expected to deal with it. Since whatever we define is supposed to be simple I don't see a problem here.

**Comment by jonblower** [comment]
All looks good to me. Some qs:

 1. How about `urlTemplate` rather than `tileTemplate`?
 2. We would need to make it clear that the `{t}` etc is the tile index in that dimension, not the index of the underlying complete array. So the tile indices go 0,1,2,3..., not 0,20,40,60...
 3. I like the fragment idea. Is there a precedent for this in another similar system? I guess the fragment _identifies_ the subset but does not cause the subset to be downloaded by itself - i.e. an HTTP client would download the whole document and then do the subset by itself. This is different from an OPeNDAP URL, which is the URL to only the subset.
 4. Would the shape of `byyear/0.covjson` be `[100,100]` or `[1,100,100]`? My initial thought would be the latter, then the dimensionality of the subsets is always the same as the parent, but maybe there's a good reason for collapsing 1-length dimensions. What do numpy/xarray do?
 5. Why does HTTP/2 mean that the too-many-requests problem is reduced?

**Comment by neothemachine** [comment]
1. Ok, `urlTemplate` is fine. Makes it more reusable in other contexts as well.
2. Sure, should be easy to understand, given the analogy to base map tiles from google etc.
3. Have a look at the [wiki examples](https://en.wikipedia.org/wiki/Fragment_identifier#Examples). And yes, you're right, the fragment just identifies the subset. The two ways to get a fragment/subset, either server-side via query parameters, or client-side via hash fragments, serve different use cases. But since hash fragments are particular to a media type, I think it would make sense to at least define the syntax in the spec in case anyone wants to implement something around that.
4. Well, for simplicity you could probably enforce that the dimensionality and axis order has to be the same. In numpy, well it depends how you slice. `v[0:1,:,:].shape` -> (1,100,100) or `v[0,:,:].shape` - (100,100).  But yes, let's do the first one.
5. HTTP/2: HTTP pipelining and multiplexing allow to do many simultanenous requests in arbitrary order without waiting for responses first, all in a single TCP connection. The whole JavaScript bundle-everything-in-a-single-file approach is also going away sooner or later. The JSPM guys already have a HTTP/2 server that demonstrates that the loading time is nearly identical with many small JS files vs one big bundled one. So even if clients need to fetch multiple range parameters, then this is not a disadvantage, compared to inventing some structure that could transport all in a single document.

**Comment by jonblower** [comment]
All looks good. I didn't know about the specs for fragment identifiers for CSV, PDF, HTML5 video etc. Seems like a natural approach to port this to coverages in the way you describe.

Interesting about HTTP/2, thanks.

**Comment by neothemachine** [comment]
I have thought about this, in particular how that would best integrate with the [JS API](https://github.com/Reading-eScience-Centre/coverage-jsapi/blob/master/Coverage.md). I came to the conclusion that the API should not change at all, but rather clients continue using the coverage-level subsetting functions and when they load the range, then the library automatically selects the best tileset and loads the subsetted range. The advantage is that it keeps clients simple by not exposing tiling at all, the disadvantage is that since tiling is not exposed clients cannot optimize their subsetting requests based on the defined tiles. I think this compromise is fine though for now. I will start implementing this in covjson-reader and then I could adapt the edal-json REST server to offer a clever combination of such tilesets instead of the Hydra-based fully dynamic subsetting approach. Then you could write a simple Python script for example which "crawls" a CovJSON coverage document and essentially creates a local static mirror that you could then upload to GitHub etc.

**Comment by jonblower** [comment]
>  since tiling is not exposed clients cannot optimize their subsetting requests based on the defined tiles

Yes, I think this compromise is fine. Would it be possible to expose a lower-level API that clients could use if they really want to optimise in this way?

**Comment by neothemachine** [comment]
They could just look at the raw CovJSON object in that case. A separate lower-level API probably makes sense once there are other formats that are exposed via this API and which also support fixed tilesets. OPeNDAP for example would not have tilesets.

**Comment by neothemachine** [comment]
Suggestion: `"tilesets"` instead of `"tileSets"`? since it's not written as tile sets, but tilesets in regular language.

**Comment by jonblower** [comment]
Sure. I don't feel strongly either way, particularly since "tilesets" isn't a real word anyway!

**Comment by neothemachine** [comment]
I'm finished with implementing this in covjson-reader now. I updated the CovJSON playground as well, have a look at the tiled grid example: http://reading-escience-centre.github.io/covjson-playground/#http://reading-escience-centre.github.io/covjson-playground/coverages/grid-tiled.covjson

I had to implement some strategy for selecting the "best" tileset. Based on a given subset of range data that you want to load, the library selects a tileset based on the minimum network effort. I estimate network effort as the sum of tiles to load plus the weighted values that would be received. I currently hard-coded that 1000 values have an equal effort as loading one tile. So that's the minimum over tile_count + value_count / 1000. This strategy seems to work quite well and does what you would expect. For example, if you have the choice of loading a single tile which would contain a million values (effort = 1001), vs loading 10 tiles which in total contain 10000 values (effort = 20), then the latter tileset would be chosen.

If you don't see any remaining issues with this and how the JSON looks like I would add it to the spec.

**Comment by jonblower** [comment]
That strategy sounds good. Make sure it's written up somewhere as other clients might want to use it too!

I think it all looks good and seems to work well. I assume that implementing this didn't throw up any nasty issues?

Looking at the JSON, "tilesets" does seem to stand out in a document where everything else is camelCased. I would suggest favouring "tileSets" for consistency. Although people might use "tileset" as a single word, they could also use "tile set" equally well. Given that there's not an obvious common usage, I would suggest saying its two words and therefore camel cased, then it doesn't look so strange in the context of the rest of the doc. (Sorry, I know I didn't mind earlier, but now that I can see the whole JSON document it does look anomalous.)

**Comment by neothemachine** [comment]
Ok no problem, I renamed it.

Implementing wasn't that easy (lots of index juggling) but in the end I didn't encounter any issues. The interesting part is that TiledNdArray is again (like NdArray) completely independent of any CovJSON semantics etc. It could be used in all kinds of contexts. And then it would make sense to extract all the ndarray related functionality into a separate library whose job is just to load (index-based subsets of) multi-dimensional array data.

**Comment by jonblower** [comment]
Yes, sounds very good. When we get a chance, I'd like to return to the question of specifying and accessing subsampled arrays (e.g. image pyramids). I know we have a proposed solution for this, but I do wonder if this could also be part of the same "Nd array" library as the above, i.e. independent of the rest of the coverage stuff (I won't discuss further here since this is really for a different thread).

**Comment by lewismc** [comment]
The tiled grid example now resides at http://covjson.org/playground/coverages/grid-tiled.covjson
